# (PART) BIOINFORMATIC PROCEDURES {-}
# About bioinformatics {#about-bioinformatics}

Bioinformatic processing of raw sequencing and mass spectrometry data is the  computational step that precedes statistical analyses and integration of multi-omic data. Through bioinformatic processing raw data are converted into meaningful bits of information, usually drastically decreasing the size of the data sets that are used for downstream analyses.

Raw sequencing and mass spectrometry-based data files used in holo-omic analyses are typically in the realm of gigabytes (Gb) or even terabytes (Tb). Many of the performed operations require large amounts of memory (some more than 1Tb), which makes it impossible to process data in personal computers. Instead, most bioinformatics tasks are performed in computational clusters with access to large amounts of memory and many CPUs and GPUs, which enable parallelising computational tasks thus speeding up data processing time.

However, for the sake of simplicity and practicality, the example datasets included in this Workbook have been considerably downscaled to enable reproducing the exercises in personal computers.

:::: {.graybox}
All bioinformatic analyses included in the **Holo-omics workbook** are conducted in a Unix command line Shell environment (BASH/SH). You can find the details to set-up your SHELL environment in the section [Prepare your R environment](#prepare-r).
:::

## Prepare your shell environment {#prepare-shell}

### Install miniconda {-}

If **conda** is not installed in your system, the first step is to install **miniconda** (a free minimal installer for conda, enough to run the bioinformatic analyses explained in the workbook). Miniconda installers for Linux, Mac and Windows operating systems can be found in the following website:
https://docs.conda.io/en/latest/miniconda.html

Once conda or miniconda is installed in your system, you should be able to create and manage your conda environments. You can test whether conda has been succesfully installed using the following code:

``` {sh eval=FALSE}
conda -V
#> conda 22.11.1 #or whatever version you have installed
```

### Install mamba {-}

The next step is to install **mamba**, which is a reimplementation of the conda package manager in C++, which speeds up many of the processes. Mamba can be installed through the command line using the `conda installB option.

``` {sh eval=FALSE}
conda install mamba -n base -c conda-forge
```

### Create a mamba environment {-}

``` {sh eval=FALSE}
wget https://holo-omics.github.io/bin/holo-omics-env.yaml #download installer file
mamba create -n holo-omics -f holo-omics-env.yaml #create environment
rm holo-omics-env.yaml #remove installer file
```

### Required software {-}

Bioinformatic pipelines for processing omic data require the use of dozens of software.

* bbmap
* bowtie2
* coverm
* fastp
* nonpareil
* samtools
* pigz


### Pipeline management {-}

Content to be added.

### Install software in conda environment {-}

Content to be added.

```
#Example code goes here
```

## Example data for bioinformatics {#example-data-bioinformatics}

Contents to be added here.

```
#Example code goes here
```

## Using snakemake for workflow management {#using-snakemake}

Contents to be added here.

```
#Example code goes here
```
