---
bibliography: references.bib
csl: biomed-central.csl
link-citations: true
output:
  bookdown::gitbook:
    highlight: tango
---
# Holo-omics workbook {-}

The **Holo-omics workbook** is a compilation of methodological procedures to generate, analyse and integrate holo-omic data, i.e., multi-omic data jointly generated from hosts and associated microbial communities [@Nyholm-2020; @Limborg-2018]. This resource extends the contents of the article **"A practical introduction to holo-omics"**, which aims at guiding researchers to the main critical steps and decision points to perform holo-omic studies. While the article focuses on discussing pros and cons of using multiple available options, the aim of the workbook is to compile protocols and pipelines to be implemented by researchers. The **Holo-omics Workbook** is presented in two formats:

* Website (https://holo-omics.github.io/)
* PDF document (https://holo-omics.github.io/holo-omics_workbook.pdf)

These resources are presented as two of the main final outputs of the H2020 project HoloFood. More information about this EU Innovation Action that ran between 2019 and 2023 can be found in the [HoloFood section][HoloFood] in this workbook, the [HoloFood Website](http://www.holofood.eu) and the [CORDIS website](https://cordis.europa.eu/project/id/817729).  

### Contents {-}

* **[Introduction](#holo-omics)**: general information about holo-omics, employed data types and study design considerations.
* **[Laboratory procedures](#about-labwork)**: methods and procedures for generating raw omic data of hosts and microbial communities.
* **[Bioinformatic procedures](#about-bioinformatics)**: methods and procedures for processing raw omic data into quantitative datasets to be analysed through statistics.
* **[Statistical procedures](#about-statistics)**: methods and procedures for analysing and integrating holo-omic data.

### Protocols, exercises and tutorials {-}

The workbook contains example data and bits of code (mostly shell and R) to reproduce data generation and analysis procedures. Code boxes look like the following:

```
shao4d_perm <- shao4d %>%
  tax_transform("identity", rank = "genus") %>%
  dist_calc("aitchison") %>%
  dist_permanova(
    variables = c("birth_mode", "sex", "number_reads"),
    n_perms = 99, # you should use more permutations in your real analyses!
    n_processes = 1
  )
#> Dropping samples with missings: 15
#> 2022-11-24 01:15:20 - Starting PERMANOVA with 99 perms with 1 processes
#> 2022-11-24 01:15:21 - Finished PERMANOVA

shao4d_perm %>% perm_get()
#> Permutation test for adonis under reduced model
#> Marginal effects of terms
#> Permutation: free
#> Number of permutations: 99
#>
#> vegan::adonis2(formula = formula, data = metadata, permutations = n_perms, by = by, parallel = parall)
#>               Df SumOfSqs      R2       F Pr(>F)   
#> birth_mode     1    10462 0.09055 29.3778   0.01 **
#> sex            1      402 0.00348  1.1296   0.31   
#> number_reads   1     1117 0.00967  3.1364   0.01 **
#> Residual     287   102209 0.88462                  
#> Total        290   115540 1.00000                  
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

### How to cite this work {-}
Instructions to cite this work will be eventually added.

### Acknowledgement {-}
This project has received funding from the European Unionʼs Horizon 2020 research and innovation programme under grant agreement No 817729.
